Blog/Blog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Blog.Bus;
using Blog.Command.Commands.Post;
using Blog.Command.Handlers.Post;
using Blog.Extensions;
using Blog.Query;
using Blog.Query.Models.Post;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    public class PostController : Controller
    {
        private readonly Lazy<IPostsRepository> _postsRepo;
        private readonly ICommandBus _commandBus;

        public PostController(ICommandBus commandBus, Lazy<IPostsRepository> postsRepo)
        {
            _postsRepo = postsRepo;
            _commandBus = commandBus;
        }
        public IActionResult Index(int page = 1, int pageSize = 20, int? categoryId = null)
        {
            return View(
                            _postsRepo.Value.GetPostsForViewing(page, pageSize, categoryId)
                       );
        }

        public IActionResult Comment(int id, string author, string comment)
        {
            _commandBus.ProcessCommand(new AddCommentToPost(id,author,comment));
            return RedirectToAction("Details", "Post", new {id = id});
        }

        public IActionResult DeleteComment(int id)
        {
            _commandBus.ProcessCommand(new DeleteComment(id));
            return Redirect(Request.Headers["Referer"].ToString());
        }

        public IActionResult Details(int id)
        {
            var post = _postsRepo.Value.GetPostWithComments(id);
            if (post != null)
            {
                return View(post);
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Action = "Create";
            return View("AddEditPost", new Post());
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                _commandBus.ProcessCommand(new AddPost(post.CategoryId, post.Title, post.Description, post.Content.Replace("\r", "").Replace("\n", "<br />"), DateTime.Now, HttpContext.User.GetUserId().Value));
                return RedirectToAction("Posts", "Dashboard");
            }
            ViewBag.Action = "Create";
            return View("AddEditPost", post);
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var post = _postsRepo.Value.GetPostById(id);
            if (post != null)
            {
                ViewBag.Action = "Edit";
                return View("AddEditPost", post);
            }
            return RedirectToAction("Posts", "Dashboard");
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                _commandBus.ProcessCommand(new EditPost(post.Id, post.CategoryId, post.Title, post.Description, post.Content));
                return RedirectToAction("Posts", "Dashboard");
            }
            ViewBag.Action = "Edit";
            return View("AddEditPost", post);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(int id)
        {
            _commandBus.ProcessCommand(new DeletePost(id));
            return RedirectToAction("Posts", "Dashboard");
        }
    }
}

Blog/Blog/ViewComponents/CategoriesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Query;
using Microsoft.AspNetCore.Mvc;

namespace Blog.ViewComponents
{
    public class CategoriesViewComponent: ViewComponent
    {
        private readonly ICategoriesRepository _categories;

        public CategoriesViewComponent(ICategoriesRepository categories)
        {
            _categories = categories;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _categories.GetCategoriesWithPostCounts();
            return View(categories);
        }
    }
}

Blog/Blog/ViewComponents/CategoryDropdownViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Query;
using Microsoft.AspNetCore.Mvc;

namespace Blog.ViewComponents
{
    public class CategoryDropdownViewComponent: ViewComponent
    {
        private readonly ICategoriesRepository _categoriesRepository;

        public CategoryDropdownViewComponent(ICategoriesRepository categoriesRepository)
        {
            _categoriesRepository = categoriesRepository;
        }
        public IViewComponentResult Invoke(int? selectedValue, string name)
        {
            ViewBag.Name = name;
            ViewBag.Value = selectedValue;
            var categories = _categoriesRepository.GetCategories(); 
            return View(categories);
        }
    }
}

Blog/Blog/Views/Post/AddEditPost.cshtml
@model Blog.Query.Models.Post.Post
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.PageHeader = "Dodaj nowy post";
}

@section styles{
    <script src="~/vendor/ckeditor/ckeditor.js"></script>
}

@section scripts{
    <script src="~/admin/js/editor.js"></script>
    <script>
        $(function() {
            initEditor();
            $("form").submit(function() {
                $("#@Html.IdFor(x=> x.Content)").val(CKEDITOR.instances.editor.getData());
            });
        })
    </script>
}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <form action="@Url.Action((string)ViewBag.Action)" method="post" class="form-horizontal">
            <input asp-for="Id" type="hidden" />
            <div class="form-group">
                <label class="col-sm-2 control-label">Kategoria: </label>
                <div class="col-sm-10">
                    @await Component.InvokeAsync("CategoryDropdown", new { selectedValue = Model.CategoryId, name = Html.NameFor(x => x.CategoryId) })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Tytuł: </label>
                <div class="col-sm-10">
                    <input asp-for="Title" type="text" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Podtytuł: </label>
                <div class="col-sm-10">
                    <input asp-for="Description" type="text" class="form-control" />
                </div>
            </div>
            <input asp-for="Content" type="hidden" />

            <div class="grid-container">
                <div class="grid-width-100">
                    <textarea id="editor">
                           @Html.Raw(Model.Content)
                    </textarea>
                </div>
            </div>
            <br />
            <button id="save" class="btn-lg pull-right btn btn-primary">Zapisz</button>
        </form>
    </div>
</div>

Blog/Blog/Views/Post/Details.cshtml
@using Blog.Query.Models.Post
@model Blog.Query.Models.Post.PostWithComments
@{
    ViewBag.BannerImage = "/img/post-bg.jpg";
    ViewBag.BannerHeader = Model.Title;
}

@section styles
    {
    <link href="~/css/comments.css" rel="stylesheet" />
    <style>
        .desc-highlight {
            color: #f3bfbf;
        }

        .comment-container {
            padding: 15px;
            border-top: 1px solid #888;
            border-bottom: 1px solid #888;
            margin-bottom: 5px;
        }

        form textarea {
            resize: none;
            height: 150px;
            margin: 5px 0;
        }

        .delete-comment-link {
            font-size: 0.8em;
        }
    </style>
}

@section BannerDescription{
    @Model.Description
}

<div class="col-lg-8 col-md-10 mx-auto">
    <div>
        <h2>@Model.Title</h2>
        <h3>@Model.Description</h3>
        <span>
            Dodano przez <span class="desc-highlight">@Model.UserName</span> dnia @Model.PostDate.ToString("dd/MM/yyyy") w kategorii <a href="@Url.Action("Index", "Post", new {id = Model.CategoryId})" class="desc-highlight">@Model.CategoryName</a>
        </span>
    </div>
    <hr />
    <div>
        @Html.Raw(Model.Content)
    </div>
    <hr />
    <h3>Komentarze (@Model.Comments.Count)</h3>
    <hr />
    @if (Model.Comments.Any())
    {
        foreach (var comment in Model.Comments)
        {
            Html.RenderPartial("_CommentPartial", comment);
        }
    }
    else
    {
        <h4 class="text-center">Brak komentarzy</h4>
    }
    <hr />
    @using (Html.BeginForm("Comment", "Post", new { id = Model.Id }))
    {
        <input required type="text" name="author" class="form-control" placeholder="Autor komentarza" />
        <textarea required name="comment" class="form-control"></textarea>
        <button type="submit" class="pull-right btn btn-sm btn-primary">Wyślij</button>
    }
</div>

@section Scripts
    {
    <script>
        $(function () {
            $(".delete-comment-link").click(function() {
                if (confirm("Czy na pewno chcesz usunąć ten komentarz?")) {
                    $(this).closest("form").submit();
                }
            });
        });
    </script>
}

Blog/Blog/Views/Post/Index.cshtml
@using Blog.Query.Models.Post
@model IEnumerable<Blog.Query.Models.Post.PostWithCategoryAndUsername>
@{
    ViewBag.BannerImage = "/img/home-bg.jpg";
    ViewBag.BannerHeader = "CQRS Blog";
}

@section styles
{
    <style>
        .category-list li.selected {
            text-decoration: underline;
        }
    </style>
}

@section BannerDescription{
    Strona przygotowana na zajęcia ZTP
}

<div class="col-md-2 col-lg-4">
    @await Component.InvokeAsync("Categories")
</div>
<div class="col-lg-8 col-md-10">
    @foreach (var post in Model)
    {
        Html.RenderPartial("_PostListItemPartial", post);
    }
    @if (!Model.Any())
    {
        <h3 class="text-center">Brak wpisów</h3>
    }
</div>